version: "3"

services:
  core:
    image: benjijang/maiz-server
    env:
      - NODE_ENV: production
    depends_on:
      - mazedraw
    ports:
      - 8000:80
    links:
      - mazedraw
    build:
      context: .
      dockerfile: Dockerfile

  mazedraw:
    image: benjijang/maiz-mazedraw
    env:
      - PYTHON_ENV: production
    expose:
      - 3000
    build:
      context: mazedraw
      dockerfile: Dockerfile
    stop_signal: SIGINT
