name: Deploy
on: push

jobs:
  deploy:
    name: Docker compose deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and deploy with docker compose
      run: docker-compose up -d --build
